name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          apt-get update -y && apt-get install -y git git-core libxml2-dev libxslt-dev python3.8-dev
          python -m pip install --upgrade pip
          pip install -r requirements.freeze.txt
    - name: Make output folder
      run: mkdir _build
    - name: Clone master branch
      run: git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" --branch gh-pages --single-branch ./_build # git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_ACTOR}/${GITHUB_ACTOR}.github.io.git" --branch master --single-branch ./_build
    - name: Generate static pages
      run: BASE_URL="https://"${GITHUB_REPOSITORY/\//.github.io\/} sphinx-build -W -D language=ru -b html . _build
